### PR TITLE
Added support for toggling pianobar (a pandora service for cli).

### PR DESCRIPTION
**Pull request by jfornoff**
Hi Conner,

thanks for making this tool, I enjoy it a lot!
I've added toggling for the [pianobar](http://6xq.net/projects/pianobar/) pandora client and figured someone else might enjoy it as well.

If you think this is superfluous, feel free to decline.

Cheers!
Jan

### CODE REVIEW

**Comment by connermcd** [comment]
Hi, Jan! Thanks for the PR. I'm really glad you've gotten some use out of `gtd`. Thank you also for introducing me to `pianobar` - it's a very cool tool. I'll look into this soon.

**Comment by connermcd** [comment]
I think `pianobar` is a very cool tool and would be neat to integrate with gtd. As it is, you can already accomplish this without editing the source by defining `$CUSTOM_CMD` in your `~/.gtdrc`.

However, it would be interesting to further integrate it so that you don't have to run two processes (one for `gtd` and one for `pianobar`). It could run `pianobar` as a subshell and report the current artist and/or allow you to use the `pianobar` commands from with `gtd`. Obviously this level of integration would be quite a bit more work, but since `pianobar` is so shell friendly and has a rudimentary event system, it is possible.

Let me think this over some more. I appreciate the suggestions!

**Comment by jfornoff** [comment]
I like your idea alot! That might be a chance for me to beef up on my shell scripting skills, will give it some thought as well and get back to you with it.

**Comment by connermcd** [comment]
[Here's](b32ce32289ed84c422c737dcf25fc9111a9c4171) some basic integration that makes `gtd` paternalize `pianobar` and wait until a `songstart` event to disown it. This should allow the user time to login and/or choose a station. Still some kinks to be ironed out.

**Comment by jfornoff** [comment]
Really nice, good job!

For login purposes, pianobar permits storing your login credentials in the config file and logs in automatically in that case, so that's an option as well.

I'll definitely try it out when i get home!

**Comment by jfornoff** [comment]
https://github.com/PromyLOPh/pianobar/blob/master/contrib/config-example
Config file reference FYI!

**Comment by jfornoff** [comment]
Heyo Conner,

sorry for running late.
Is that solution working for you right now?
As for me, I am pretty certain that Pianobar ist not getting my station selection input due to being in a subshell right away.

Maybe there is a way to pipe STDIN to $HOME/.config/pianobar/ctl until the songstart event or something in that sense, though we still have a problem with controlling pianobar while working.

Do you think this is worth implementing?

Cheers,
Jan

**Comment by connermcd** [comment]
Yes, you're correct. Sorry I haven't responded - things are getting busy! I don't know that I'll have time to implement it, but if it's worth it to you then you should go for it. Cheers!

**Pull request closed without merging**
