### PR TITLE
Edit configuration for tmux status bar in README.md

### PR DESCRIPTION
**Pull request by casdijkman**
Fix performance issue and make configuration more clear

### CODE REVIEW

**Comment by connermcd** [comment]
The only file changed for these commits is the readme. Did you stage your changes before committing?

**Comment by casdijkman** [comment]
Yes, I only meant to change the README, the suggested tmux configuration there caused some problems on my system

**Comment by connermcd** [comment]
Well there are four commits for a one line change...

**Comment by connermcd** [comment]
Do you mind squashing them into one

**Comment by casdijkman** [comment]
No problem

**Pull request closed without merging**
